### ISSUE TITLE
doesn't work at windows 11

### ISSUE THREAD

**Issue by 3xploiton3** [elliottophellia/kiriha#1]
![image](https://github.com/elliottophellia/kiriha/assets/19517680/8da5c024-13ed-4423-9d27-af2df6154786)

**Comment by elliottophellia** [comment]
Can you remove error_reporting line in the code and try to run it again? If there is error i hope you can screenshot it and post it here.

**Comment by 3xploiton3** [comment]
did you mean this line?
![image](https://github.com/elliottophellia/kiriha/assets/19517680/93a4e013-9b22-49a8-b8a3-77c96e138784)

![image](https://github.com/elliottophellia/kiriha/assets/19517680/65483013-86e2-47f3-9f5f-690453f60426)

**Comment by elliottophellia** [comment]
Ah, i think it's because you don't allow curl extension in your php.ini, you can go to C:/php (or any directory where your php file saved) and find file called php.ini in same folder with php.exe, then open it and find line with ";extension=curl" remove the semicolon to allow it.

**Comment by 3xploiton3** [comment]
no file called php.ini on me,
![image](https://github.com/elliottophellia/kiriha/assets/19517680/91b1379a-6fad-471b-9d94-36199af36d52)

i remove and change "extension=curl" at php.ini-development & production
![image](https://github.com/elliottophellia/kiriha/assets/19517680/2df4cef1-2f67-4eee-98ff-49ae62b4826b)

**Comment by elliottophellia** [comment]
Rename either development or production into php.ini

**Comment by 3xploiton3** [comment]
ok, work, but its miss interpret 
![image](https://github.com/elliottophellia/kiriha/assets/19517680/1ee0e306-c239-4e01-b7e1-93220465e58d)
![image](https://github.com/elliottophellia/kiriha/assets/19517680/ebcd24fd-7c67-41af-9abf-ed9f7a2e91f3)

**Comment by elliottophellia** [comment]
Well it was designed to check it via http header, so as long as it's custom 404 page without 404 header it's not gonna work lol, but that page it's kinda sus maybe better to try to fuzz it just in case

And probably you need to comment out line 81 "exit();" so it not kill the scan after first found

**Comment by 3xploiton3** [comment]
it's very not efficient if we must check manually 1 by 1 all url

![image](https://github.com/elliottophellia/kiriha/assets/19517680/9ab38f27-a76d-44fd-bc53-b6981549c213)

**Comment by elliottophellia** [comment]
Maybe I'm gonna update it soon if I have free time.

**Comment by elliottophellia** [comment]
#2
